In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings 
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
import sqlite3

conn = sqlite3.connect("../Data/diabetes_project.db")

DATA = pd.read_sql("SELECT * FROM coded_data", conn)

In [3]:
DATA['GENDER'].value_counts()

GENDER
0    712
1    600
Name: count, dtype: int64

In [13]:
DATA.columns=DATA.columns.str.strip()

In [14]:
DATA.head()

,AGE,GENDER,SUBJECT TYPE,HBA1C,PP2 [<140 mg/dl],FBS [74-110 mg/dl],BMI,WAIST TO HIP RATIO,TOBACCO,PHYSICAL ACTIVITY,ALCOHOL,SERUM TRIGLYCERIDE [<150 mg/dl],HDL CHOLESTEROL[200 mg/dl],CHOL/HDL,LDL/HDL
0,70,0,0,0,0,0,2,1,3,0,1,0,0,0,0
1,60,1,0,0,0,1,2,1,0,1,0,0,0,0,0
2,60,1,0,0,0,1,2,1,0,1,0,0,0,0,0
3,43,0,0,0,0,1,2,1,0,0,1,0,0,0,0
4,65,1,0,1,0,1,2,1,0,1,0,1,0,0,0

In [15]:
Data_female=DATA[DATA['GENDER']!=0]

In [16]:
Data_male=DATA[DATA['GENDER']!=1]

In [17]:
Data_female

,AGE,GENDER,SUBJECT TYPE,HBA1C,PP2 [<140 mg/dl],FBS [74-110 mg/dl],BMI,WAIST TO HIP RATIO,TOBACCO,PHYSICAL ACTIVITY,ALCOHOL,SERUM TRIGLYCERIDE [<150 mg/dl],HDL CHOLESTEROL[200 mg/dl],CHOL/HDL,LDL/HDL
1,60,1,0,0,0,1,2,1,0,1,0,0,0,0,0
2,60,1,0,0,0,1,2,1,0,1,0,0,0,0,0
4,65,1,0,1,0,1,2,1,0,1,0,1,0,0,0
5,75,1,0,0,0,1,2,1,1,1,0,0,1,0,0
8,48,1,0,0,0,1,2,1,0,1,0,2,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,50,1,1,2,2,2,0,1,0,0,0,2,0,0,0
1308,54,1,1,2,1,2,0,1,0,0,0,2,0,0,0
1309,50,1,1,2,1,0,0,1,0,0,0,1,1,0,0
1310,51,1,1,2,2,2,1,1,0,1,0,0,1,0,0
1311,55,1,1,0,1,1,1,1,0,1,0,2,0,0,0

In [18]:
Data_female.drop('GENDER',axis=1,inplace=True)

In [20]:
from lifelines import CoxPHFitter
cox_ph=CoxPHFitter()
cox_female=cox_ph.fit(Data_female,'AGE','SUBJECT TYPE')
cox_female.print_summary()

<lifelines.CoxPHFitter: fitted with 600 total observations, 291 right-censored observations>
             duration col = 'AGE'
                event col = 'SUBJECT TYPE'
      baseline estimation = breslow
   number of observations = 600
number of events observed = 309
   partial log-likelihood = -1566.72
         time fit was run = 2026-03-07 15:07:56 UTC

---
                                 coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
HBA1C                            0.25      1.28      0.07            0.11            0.38                1.12                1.47
PP2 [<140 mg/dl]                 0.26      1.30      0.08            0.10            0.42                1.11                1.53
FBS [74-110 mg/dl]               0.13      1.14      0.09           -0.05            0.31                0.95                1.36
BMI                             -0.13      0.88      0.09           -0.30            0.04                0.74                1.04
WAIST TO HIP RATIO              -0.32      0.72      0.17           -0.65            0.01                0.52                1.01
TOBACCO                         -0.16      0.86      0.08           -0.31           -0.00                0.74                1.00
PHYSICAL ACTIVITY               -0.57      0.57      0.15           -0.86           -0.28                0.42                0.76
ALCOHOL                          0.27      1.31      0.08            0.11            0.44                1.11                1.55
SERUM TRIGLYCERIDE [<150 mg/dl]  0.01      1.01      0.07           -0.12            0.13                0.88                1.14
HDL CHOLESTEROL[200 mg/dl]      -0.19      0.83      0.11           -0.40            0.03                0.67                1.03
CHOL/HDL                         0.16      1.17      0.28           -0.39            0.70                0.68                2.02
LDL/HDL                         -0.08      0.92      0.25           -0.57            0.40                0.57                1.49

                                 cmp to     z      p  -log2(p)
covariate
HBA1C                              0.00  3.59 <0.005     11.54
PP2 [<140 mg/dl]                   0.00  3.25 <0.005      9.77
FBS [74-110 mg/dl]                 0.00  1.40   0.16      2.62
BMI                                0.00 -1.54   0.12      3.02
WAIST TO HIP RATIO                 0.00 -1.92   0.05      4.20
TOBACCO                            0.00 -2.01   0.04      4.49
PHYSICAL ACTIVITY                  0.00 -3.85 <0.005     13.07
ALCOHOL                            0.00  3.24 <0.005      9.70
SERUM TRIGLYCERIDE [<150 mg/dl]    0.00  0.09   0.93      0.10
HDL CHOLESTEROL[200 mg/dl]         0.00 -1.70   0.09      3.48
CHOL/HDL                           0.00  0.57   0.57      0.82
LDL/HDL                            0.00 -0.34   0.73      0.45
---
Concordance = 0.68
Partial AIC = 3157.44
log-likelihood ratio test = 117.44 on 12 df
-log2(p) of ll-ratio test = 62.12

In [21]:
Data_male.drop('GENDER',axis=1,inplace=True)

In [23]:
cox_male=cox_ph.fit(Data_male,'AGE','SUBJECT TYPE')
cox_male.print_summary()

<lifelines.CoxPHFitter: fitted with 712 total observations, 338 right-censored observations>
             duration col = 'AGE'
                event col = 'SUBJECT TYPE'
      baseline estimation = breslow
   number of observations = 712
number of events observed = 374
   partial log-likelihood = -2005.35
         time fit was run = 2026-03-07 15:08:10 UTC

---
                                 coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
HBA1C                            0.10      1.10      0.06           -0.03            0.22                0.97                1.25
PP2 [<140 mg/dl]                 0.15      1.16      0.07            0.01            0.29                1.01                1.34
FBS [74-110 mg/dl]               0.50      1.65      0.09            0.33            0.68                1.39                1.96
BMI                              0.02      1.02      0.09           -0.15            0.19                0.86                1.21
WAIST TO HIP RATIO              -0.16      0.86      0.18           -0.52            0.21                0.60                1.23
TOBACCO                         -0.09      0.92      0.06           -0.21            0.03                0.81                1.03
PHYSICAL ACTIVITY               -0.83      0.44      0.20           -1.21           -0.44                0.30                0.64
ALCOHOL                          0.28      1.33      0.07            0.15            0.41                1.17                1.51
SERUM TRIGLYCERIDE [<150 mg/dl]  0.12      1.12      0.06           -0.00            0.24                1.00                1.26
HDL CHOLESTEROL[200 mg/dl]      -0.17      0.84      0.10           -0.36            0.02                0.70                1.02
CHOL/HDL                         0.07      1.08      0.37           -0.64            0.79                0.53                2.21
LDL/HDL                         -0.07      0.93      0.41           -0.88            0.74                0.41                2.09

                                 cmp to     z      p  -log2(p)
covariate
HBA1C                              0.00  1.53   0.13      2.99
PP2 [<140 mg/dl]                   0.00  2.09   0.04      4.79
FBS [74-110 mg/dl]                 0.00  5.69 <0.005     26.19
BMI                                0.00  0.22   0.83      0.27
WAIST TO HIP RATIO                 0.00 -0.84   0.40      1.33
TOBACCO                            0.00 -1.46   0.14      2.79
PHYSICAL ACTIVITY                  0.00 -4.23 <0.005     15.36
ALCOHOL                            0.00  4.31 <0.005     15.90
SERUM TRIGLYCERIDE [<150 mg/dl]    0.00  1.92   0.05      4.20
HDL CHOLESTEROL[200 mg/dl]         0.00 -1.74   0.08      3.62
CHOL/HDL                           0.00  0.20   0.84      0.25
LDL/HDL                            0.00 -0.17   0.86      0.21
---
Concordance = 0.67
Partial AIC = 4034.70
log-likelihood ratio test = 144.69 on 12 df
-log2(p) of ll-ratio test = 80.29

In [24]:
import joblib

joblib.dump(cox_male, "../Models/cox_male.pkl")
joblib.dump(cox_female, "../Models/cox_female.pkl")

['../Models/cox_female.pkl']